# env
env_name: "lap-joint"
offset: "0mm"
dataset_name: "LAP_PYBULLET_0mm_TVFS_FD_WS8_NR2_NB3_CR100"
sensor_used_in_sampling: ["ft", "depthmap"]

# GPU
use_gpu: True                                         # set to True during training dense reward, set to False when doing inference in RD2 training

# FT sample
ft_window_size: 8                                     # number of frame to concatenate into one observation
left_append: False                                    # if true, left in right out (left element in seq is the most current obs); else, right in left out

# sampler                    
sampler: "TemporalVariantForwardSampler"             
num_expert_rollouts: 2                                # number of expert rollouts used to perform backward sampling
num_seeds: 1                                          # <SET TO 1> number of seed to use for generating samples at each depth
num_samples: 10
num_branches: 3                                       # number of samples to generate at each depth
num_steps_per_branch: 10
control_rate: 100                                     # interval (in terms of timesteps) to create a depth
stop_sampling_threshold: 0.5                          # [NAIVE BACKWARD SAMPLER ONLY] threshold to control the end of sampling
train_test_split: 0.5

# sampling rollback control (no need to change)
num_rollbacks_per_trial: 3
restore_threshold: 0.000005
num_rollbacks_final_trial: 15

# specific to temporal variant sampler
use_history: False
control_angle_goal: 15
control_angle_start: 45
control_angle_mid: 85

# network architecture
ft_network_type: "LSTM"                                # choose one: "MLP" / "LSTM"
z_dim: 128                                             # try 48
sensor_used_in_model: ["ft", "depthmap"]               # must have: "ft" , can have: "depthmap", "image". sensors used here must be contained in sensor_used_in_sampling

# training
initialize_weights: True
batch_size: 64
num_workers: 0
lr: 0.0003
weight_decay: 0.000005
num_iters: 1000000
log_freq: 200
save_freq: 200

# loss
depth_margin: 2
within_threshold: 0.04
outside_threshold: 0.04
reconstruction_lambda: 0.2
temporal_enforcement_lambda: 10.0
# comparison_lambda: 10.0

